spring:
  application:
    name: coworking-reservations

  profiles:
    default: dev

  jpa:
    open-in-view: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - circuitbreakers

  endpoint:
    health:
      show-details: when_authorized

app:
  security:
    jwt:
      expiration: 3600000